### ISSUE TITLE
Agent compilation failed

### ISSUE THREAD

**Issue by reloc2** [Faisal-P27/WAREED-DNS-C2#1]
root@ubuntu-linux-22-04-02-desktop:/home/parallels/WAREED-DNS-C2/Agent# make BUILD_TYPE=exe
Source/Core/Tasks/Modules/Execution.c: In function ‘ds_rename_handle’:
Source/Core/Tasks/Modules/Execution.c:163:2: error: unknown type name ‘FILE_RENAME_INFO’
  163 |  FILE_RENAME_INFO fRename;
      |  ^~~~~~~~~~~~~~~~
Source/Core/Tasks/Modules/Execution.c:168:9: error: request for member ‘FileNameLength’ in something not a structure or union
  168 |  fRename.FileNameLength = sizeof(lpwStream);
      |         ^
In file included from /usr/share/mingw-w64/include/minwindef.h:163,
                 from /usr/share/mingw-w64/include/windef.h:9,
                 from /usr/share/mingw-w64/include/windows.h:69,
                 from Include/Core/Tasks/Modules/Execution.h:4,
                 from Source/Core/Tasks/Modules/Execution.c:6:
Source/Core/Tasks/Modules/Execution.c:169:23: error: request for member ‘FileName’ in something not a structure or union
  169 |  RtlCopyMemory(fRename.FileName, lpwStream, sizeof(lpwStream));
      |                       ^
Source/Core/Tasks/Modules/Execution.c:171:45: error: ‘FileRenameInfo’ undeclared (first use in this function)
  171 |  return SetFileInformationByHandle(hHandle, FileRenameInfo, &fRename, sizeof(fRename) + sizeof(lpwStream));
      |                                             ^~~~~~~~~~~~~~
Source/Core/Tasks/Modules/Execution.c:171:45: note: each undeclared identifier is reported only once for each function it appears in
Source/Core/Tasks/Modules/Execution.c: In function ‘ds_deposite_handle’:
Source/Core/Tasks/Modules/Execution.c:179:2: error: unknown type name ‘FILE_DISPOSITION_INFO’
  179 |  FILE_DISPOSITION_INFO fDelete;
      |  ^~~~~~~~~~~~~~~~~~~~~
Source/Core/Tasks/Modules/Execution.c:182:9: error: request for member ‘DeleteFileA’ in something not a structure or union
  182 |  fDelete.DeleteFile = TRUE;
      |         ^
Source/Core/Tasks/Modules/Execution.c:184:45: error: ‘FileDispositionInfo’ undeclared (first use in this function)
  184 |  return SetFileInformationByHandle(hHandle, FileDispositionInfo, &fDelete, sizeof(fDelete));
      |                                             ^~~~~~~~~~~~~~~~~~~
make: *** [makefile:36: all] Error 1

OS:
![WechatIMG84](https://github.com/Faisal-P27/WAREED-DNS-C2/assets/36962741/98a766dd-7fce-4061-af0e-73643ef44326)

**Comment by Faisal-P27** [comment]
It appears that the issue with your Agent compilation is due to using an outdated version of MinGW-w64 (versions below 10). To address this problem, you have a couple of options:

1- Upgrade MinGW-w64: Update your MinGW-w64 to version 10 or higher. 
2- Simply modify the Source Code: As an alternative, you can manually adjust the source code. Go to the file located at /Agent/Include/Core/Tasks/Modules/Execution.h and uncomment the code between lines 16 and 60.  This step acts as a workaround by enabling code that is compatible with older versions of MinGW-w64.
